#!/bin/bash

BACK_NAME=$(date +%F)
LISTBCK="/tmp/ha-backups"
BCKDIR="/home/hassio/backup"
NBCK=5

# Create ha core backup
echo "Create new backup $BACK_NAME"
ha backups new --name $BACK_NAME

# Purge old backup
ls -t1 "$BCKDIR" | rev | cut -c5- | rev >"$LISTBCK"
n=1
while read -r backname; do
	if [ "$n" -gt "$NBCK" ]; then
		echo "Deleting $backname"
		ha backups rm "$backname"
	fi
	n=$((n + 1))
done <"$LISTBCK"
