# change format
$ActionForwardDefaultTemplate RSYSLOG_SyslogProtocol23Format

# warning errors
#*.warning @srvnas.ad.rroveri.com
*.warning @srvlog.ad.rroveri.com

# auth logging
#auth.* @srvnas.ad.rroveri.com
auth.* @srvlog.ad.rroveri.com

# local0 logging
local0.* -/var/log/local0.log
#local0.* @srvnas.ad.rroveri.com
local0.* @srvlog.ad.rroveri.com
local0.* stop
