#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import subprocess
import sys
import os
#############
def encode(inp, outp):
        cmd0 = ["ffmpeg", "-i", inp, "-c:a", "libmp3lame", "-b:a", "128k", outp]
        subprocess.call(cmd0)
############
def move(inp):
        cmd1 = ["mv", inp, "/Users/rick/GoogleDrive/Musica/2017"]
        subprocess.call(cmd1)
############
songs = sys.argv[1:]

for song in songs:
        if not os.path.isfile(song):
                print("Canzone non trovata:", song)
                sys.exit(1)
		
for song in songs:
        songa, tmp = song.partition(".")[::2]
        newName = song.split("-")
        del newName[-1]
        newName = "-".join(newName)+".mp3"
        encode(song, newName)
        nome = newName
        move(nome)
        os.remove(song)
