#!/usr/bin/env python3

import subprocess
import sys
import os

path =  os.environ.get('GIT_HOME_DIR')

if (path == None):
	print("can't find GIT_HOME_DIR")
	sys.exit(1)

dirs = os.listdir(path)
dirs = list(filter(lambda dir: os.path.isdir(path+dir), dirs))
dirs = list(filter(lambda dir: os.path.exists(path+dir+"/.git"), dirs))

os.chdir(path)

print("#####")
for dir in dirs:
	print("Updating", dir)
	os.chdir(path+dir)
	subprocess.call(["git", "pull"])
	print("#####")
