#!/usr/bin/env python3

import subprocess
import sys
import os

path = "/Users/rick/Git/"

dirs = os.listdir(path)
dirs = list(filter(lambda dir: os.path.isdir(path+dir), dirs))
dirs = list(filter(lambda dir: os.path.exists(path+dir+"/.git"), dirs))

os.chdir(path)

print("#####")
for dir in dirs:
	print("Updating", dir)
	os.chdir(path+dir)
	subprocess.call(["git", "pull"])
	print("#####")
