#!/bin/sh
###
# Backing up core
###
CORE_DIR="/home/hassio/backup"

CORE_BACKUP_NAME=$(ha core info | grep last_version | awk -F ': ' '{print $2}')
echo "Backup version $CORE_BACKUP_NAME"

CORE_BACKUP_CODE=$(ha snap new --name $CORE_BACKUP_NAME | awk -F ': ' '{print $2}')
echo "Backup name $CORE_BACKUP_CODE"

cd $CORE_DIR
echo "$CORE_BACKUP_CODE.tar $CORE_BACKUP_NAME" >> backup.log
####
# Backing up hassio
####
BACKUP_DIR=/tmp
BACKUP_NAME=$(date +%F).hassio.zip
REMOTE_DIR=/volume1/rick/hassio_backups

echo "Creating ZIP"
cd /home
zip -8 -qrn ".tar" "$BACKUP_DIR/$BACKUP_NAME" hassio -x "*.sock"

echo "Copy to remote location"
scp "$BACKUP_DIR/$BACKUP_NAME" "rick@192.168.1.150:$REMOTE_DIR" 2> /dev/null

# Remove created zip file
rm "$BACKUP_DIR/$BACKUP_NAME"
