#!/bin/sh

VOL_PID=/tmp/volume_listener.pid

sudo /usr/bin/nohup /Users/rick/Git/script/python/volume_listener.py &> /dev/null &
LISTENER_PID=$(echo $!)
echo Started on PIN $LISTENER_PID
echo $LISTENER_PID > $VOL_PID.$(date +%s)
echo $LISTENER_PID > $VOL_PID
