#!/bin/sh

LOCAL_DIR=/mnt/oneplus
REMOTE_DIR=/volume1/oneplus

if ! command -v adb-sync &>/dev/null; then
  echo "Please install adb-sync"
  exit 1
fi

if [[ ! -d "$LOCAL_DIR/sdcard" ]]; then
  echo '######### MOUNT NFS #########'
  pkexec mount -t nfs -o nfsvers=4,noexec srvnas.roveri.local:$REMOTE_DIR $LOCAL_DIR
  if [[ $? != 0 ]]; then
    echo "Cannot mount nfs"
    exit 1
  fi
fi

echo '######### ANDROID BACKUP #########'
# -d delete | -o out | -j junk | -f folders | -i device_id
android-backup -dj -i 9969309f -o "$LOCAL_DIR/sdcard" -f "$LOCAL_DIR/backup_dir.txt" $1
echo '############## END ##############'
