---
version: "3.8"
services:
  wg-easy:
    restart: unless-stopped
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.rroveri.com
      - PASSWORD=recall5-shorter-spray
      - WG_DEFAULT_DNS=10.0.0.233,10.0.0.234
      - WG_DEFAULT_ADDRESS=10.0.1.x
      - WG_ALLOWED_IPS=10.0.0.0/24
    # - WG_PERSISTENT_KEEPALIVE=120
    mem_limit: 50m

    volumes:
      - /root/wireguard/data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      #  - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
networks:
  default:
    name: "homelab_net"
    external: true
