#!/bin/sh

if [ -z "$1" ]; then
  echo "Provide version number"
  exit 1
fi

cd /home/rick/develop || exit 1

sudo docker buildx build --platform linux/arm64 --load -t "devel:$1" .
sudo docker save "devel:$1" | pv | ssh srvnas /usr/local/bin/docker load

