#!/bin/bash

sudo mount -t drvfs P: /mnt/p
echo "- mounted drive"

if [ -z "$1" ]; then
  echo "Provide folder to scan"
  exit 1
fi

find "$1" -iname "*.HEIC" -print0 | xargs -0 -n 1 -P4 ./heic-convert 
#-exec ./heic-convert {} \;
echo "- finished"
