# yamllint disable-file
---
- name: "Configure debconf"
  ansible.builtin.debconf:
    name: "nslcd"
    question: "{{ item.question }}"
    vtype: "{{ item.vtype }}"
    value: "{{ item.value }}"
  loop:
    - {
        question: "nslcd/ldap-uris",
        vtype: "string",
        value: "ldap://srvdc1.roveri.local",
      }
    - { question: "nslcd/ldap-auth-type", vtype: "string", value: "none" }
    - { question: "nslcd/ldap-starttls", vtype: "boolean", value: "false" }
    - {
        question: "nslcd/ldap-base",
        vtype: "string",
        value: "dc=ad,dc=rroveri,dc=com",
      }
    # - {
    #     question: "libnss-ldapd/nsswitch",
    #     value: "passwd, group, shadow",
    #     vtype: "multiselect",
    #   }
  notify: Reconfigure nslcd
- name: "Install packages"
  ansible.builtin.apt:
    state: present
    name:
      - libnss-ldapd
      - libpam-ldapd
      - nslcd
      - sudo
- name: Make sure nslcd conf is up to date
  ansible.builtin.lineinfile:
    path: /etc/nslcd.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - { regexp: "^base", line: "base dc=ad,dc=rroveri,dc=com" }
    - { regexp: "^uri", line: "uri ldap://srvdc1.roveri.local" }
  notify: Restart nslcd
- name: Update nsswitch.conf for LDAP integration
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^passwd:", line: "passwd:         files systemd ldap" }
    - { regexp: "^group:", line: "group:          files systemd ldap" }
    - { regexp: "^shadow:", line: "shadow:         files ldap" }
- name: Ensure pam_mkhomedir.so is setup
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
- name: "Configure sudo"
  community.general.sudoers:
    name: ldap
    state: present
    group: admins
    validation: required
    commands: ALL
    runas: ALL
    nopassword: false
