#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import subprocess
import sys
import os.path


def encode(inp, outp):
    cmd = ["convert", inp, outp]
    subprocess.call(cmd)


if len(sys.argv) > 2:
    if len(sys.argv[1]) == 3:
        images = sys.argv[2:]
        ext = sys.argv[1]

        i = input("do you want to remove the old one? [Y/n] ")
        for image in images:
            newName = "_".join(image.split(".")[:-1]) + "." + ext
            encode(image, newName)
            if (i.lower() == 'y'):
                print("remove image", image)
                os.remove(image)
    else:
        print("wrong extension")
else:
    print("not enaught element")
