#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import subprocess
import sys
import os

##################
path = "~/Music/"
def encode(inp):
	cmd = ["youtube-dl", "-x", "--prefer-ffmpeg", "--audio-format", "mp3", "--exec", " mv {} "+path, "-o %(title)s.%(ext)s", inp]
	subprocess.call(cmd)
##################
urls = sys.argv[1:]

for url in urls :	
	encode(url)
