---
- name: Check if docker is present
  ansible.builtin.command: which docker
  register: docker_installed
  failed_when: false
  changed_when: false
- name: Include docker role
  ansible.builtin.include_tasks: docker.yml
  when: docker_installed.rc == 0
