---
- name: "Check if docker is present"
  ansible.builtin.command: which docker
  register: docker_installed
  failed_when: false
  changed_when: false
- name: List all Docker images
  ansible.builtin.shell:
    cmd: 'docker image ls --format {% raw %}"{{.Repository}}:{{.Tag}}"{% endraw %} | grep -v none' # noqa risky-shell-pipe
  register: docker_images_list
  changed_when: false
  when: docker_installed.rc == 0
- name: Pull all the images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop: "{{ docker_images_list.stdout_lines }}"
  when: docker_installed.rc == 0
