---
- name: Check if docker is present
  ansible.builtin.command: which docker
  register: docker_installed
  failed_when: false
  changed_when: false
- name: Include main docker task
  ansible.builtin.include_tasks: docker.yml
  when: docker_installed.rc == 0
- name: Configure docker daemon to use rsyslog
  ansible.builtin.copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    mode: "0644"
  when: docker_installed.rc == 0
