---
- name: "Homelab"
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: "Disable ipv6"
      ansible.builtin.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        sysctl_set: true
        state: present
        reload: true
    - name: "Set timezone Europe/Rome"
      community.general.timezone:
        name: "Europe/Rome"
  vars:
    bck_dir: "/home/rick/backups"
  roles:
    - backup
    - rsyslog
    - update
