---
- name: "Homelab"
  hosts: all
  serial: 3
  become: true
  remote_user: root
  tasks:
    - name: "Disable ipv6"
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: "1"
        sysctl_set: true
        state: present
        reload: true
    - name: "Set timezone Europe/Rome"
      community.general.timezone:
        name: "Europe/Rome"
    - name: "Set bash history config"
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        regexp: "^#?{{ item.key }}"
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: "HISTSIZE", value: "" }
        - { key: "HISTFILESIZE", value: "" }
        - { key: "HISTCONTROL", value: "ignoreboth:erasedups" }
        - { key: "HISTIGNORE", value: "ls:cd" }
        - { key: "export EDITOR", value: "vim" }
        - { key: "export VISUAL", value: "$EDITOR" }
    - name: "Install ldap"
      ansible.builtin.include_role:
        name: ldap
      when: ansible_facts['os_family'] == "Debian"
  vars:
    bck_dir: "/home/rick/backups"
  roles:
    - update
    - docker
    - backup
    - rsyslog
    - ssh
    - snmp
