---
- name: "Homelab"
  hosts: all
  serial: 2
  become: true
  remote_user: root
  tasks:
    - name: "Disable ipv6"
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: "1"
        sysctl_set: true
        state: present
        reload: true
    - name: "Set timezone Europe/Rome"
      community.general.timezone:
        name: "Europe/Rome"
    - name: "Set infinite history"
      lineinfile:
        path: /root/.bashrc
        regexp: "^#?{{ item }}"
        line: "{{ item }}"
        state: present
      loop:
        - "HISTSIZE="
        - "HISTFILESIZE="
  vars:
    bck_dir: "/home/rick/backups"
  roles:
    - backup
    - rsyslog
    - update
    - ssh
