---
- name: "Homelab"
  hosts: all
  # serial: 1
  become: true
  remote_user: root
  tasks:
    - name: "Disable ipv6"
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: "1"
        sysctl_set: true
        state: present
        reload: true
    - name: "Set timezone Europe/Rome"
      community.general.timezone:
        name: "Europe/Rome"
    - name: "Set bash history config"
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        regexp: "^#?{{ item.key }}"
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: "HISTSIZE", value: "" }
        - { key: "HISTFILESIZE", value: "" }
        - { key: "HISTCONTROL", value: "ignoreboth:erasedups" }
        - { key: "HISTIGNORE", value: "ls:cd" }
        - { key: "export EDITOR", value: "vim" }
        - { key: "export VISUAL", value: "$EDITOR" }
    - name: "Create vimrc file"
      ansible.builtin.file:
        path: /root/.vimrc
        state: touch
        mode: "0644"
        modification_time: preserve
        access_time: preserve
    - name: "Set vimrc config"
      ansible.builtin.lineinfile:
        path: /root/.vimrc
        regexp: "^#?{{ item }}"
        line: "{{ item }}"
        state: present
      loop:
        - "set expandtab"
        - "set shiftwidth=2"
        - "set softtabstop=2"
        - "set tabstop=2"
    - name: "Install ldap"
      ansible.builtin.include_role:
        name: ldap
      when: ansible_facts['os_family'] == "Debian"
    - name: "Configure ntp"
      ansible.builtin.include_role:
        name: ntp
      when: ansible_facts['os_family'] == "Debian"
  vars:
    bck_dir: "/home/rick/backups"
  roles:
    - update
    - docker
    - backup
    - rsyslog
    - ssh
    - snmp
