---
- name: "Run update for Debian"
  ansible.builtin.include_tasks:
    file: "debian.yml"
  when: ansible_facts['os_family'] == "Debian"
- name: "Run update for RedHat"
  ansible.builtin.include_tasks:
    file: "redhat.yml"
  when: ansible_facts['os_family'] == "RedHat"
