---
- name: "Proxy APT"
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/60proxy
    line: 'Acquire::http { Proxy "http://srvapt.roveri.local:3142"; }'
    create: true
- name: "Update package list"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
- name: "Upgrade packages"
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  notify: "Restart"
