---
- name: "Add logging config"
  ansible.builtin.copy:
    src: "90-sendlog.conf"
    dest: "/etc/rsyslog.d/90-sendlog.conf"
    mode: "0644"
  notify: "Restart rsyslog"
- name: "Configure logrotate for local0"
  ansible.builtin.lineinfile:
    create: false
    path: "/etc/logrotate.d/rsyslog"
    line: "/var/log/local0.log"
    insertbefore: '^\{'
    mode: "0644"
