---
- name: "Add logging for serverity more than info"
  ansible.builtin.lineinfile:
    create: true
    path: "/etc/rsyslog.d/90-sendlog.conf"
    line: "*.notice @srvnas.roveri.local"
    mode: 0644
  notify: 'Restart rsyslog'
- name: "Add logging for serverity more than info"
  ansible.builtin.lineinfile:
    create: true
    path: "/etc/rsyslog.d/90-sendlog.conf"
    line: "local0.* @srvnas.roveri.local"
    mode: 0644
  notify: 'Restart rsyslog'
