#!/bin/sh
test "$1" || exit 1

BACKUP_DIR="/tmp"
SRC_DIR=$(echo $1 | rev | cut -f1 -d/ | rev)
BACKUP_NAME="$SRC_DIR.tar"
REMOTE_DIR=/volume1/veeam/raspi

echo "Creating $BACKUP_NAME"
cd $1
cd ..
tar -cf "$BACKUP_DIR/$BACKUP_NAME" $SRC_DIR

echo "Copy to remote location"
scp -O -P 222 "$BACKUP_DIR/$BACKUP_NAME" "root@srvnas.roveri.local:$REMOTE_DIR"

# Remove created zip file
rm "$BACKUP_DIR/$BACKUP_NAME"
