#!/bin/sh
###
# Backing up core
###

CORE_VERSION=$(ha core info | grep last_version | awk -F ': ' '{print $2}')
echo "Homeassistant version $CORE_VERSION"

####
# Backing up hassio
####
BACKUP_DIR="/tmp"
BACKUP_NAME=$(date +%F).hassio.zip
REMOTE_DIR=/volume1/rick/hassio_backups

echo "Creating ZIP"
cd /home
zip -7 -qrn ".tar" "$BACKUP_DIR/$BACKUP_NAME" hassio -x "*.sock"

echo "Copy to remote location"
scp -P 222 "$BACKUP_DIR/$BACKUP_NAME" "root@192.168.1.220:$REMOTE_DIR"

# Remove created zip file
rm "$BACKUP_DIR/$BACKUP_NAME"

