#!/bin/bash

# find /mnt/p -name "*.HEIC" -exec ./heic-converter {} \;

file="$1"
if [[ -f $file && $file != *"recycle"* && $file != "/mnt/p/heic/"* ]]; then
	echo $file
	heif-convert $file ${file/%.HEIC/.png}
	mv $file /mnt/p/HEIC
fi
