#!/bin/sh

chsh -s $(which zsh)

cd ../dotfiles
cp .* $HOME

# PLUGINS
export ZSH_PLUGINS=~/.zsh-plugins
mkdir $ZSH_PLUGINS

# POWERLEVEL10K
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_PLUGINS/powerlevel10k
# Remove git icon
cd $HOME/.oh-my-zsh/custom/themes/powerlevel10k/internal
GIT_ICON_LINE=$(grep 'function _p9k_vcs_icon() {' p10k.zsh -n | awk -F ':' '{print $1}')
START_LINE=$(( $GIT_ICON_LINE + 1))
END_LINE=$(( $START_LINE + 6))
mv p10k.zsh p10k.zsh.tmp
sed $START_LINE','$END_LINE'd' p10k.zsh.tmp > p10k.zsh
cd $HOME

# ZSH-AUTOSUGGESTIONS
git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_PLUGINS/zsh-autosuggestions

# SUDO
mkdir $ZSH_PLUGINS/sudo
curl -s https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh -o $ZSH_PLUGINS/sudo/sudo.plugin.zsh

zsh