#!/bin/bash

dirs="*"

cd archive
for dir in $dirs; do
  echo $dir
  cd "../live/$dir"
  pwd
  for f in $dirs; do
    echo "linking $f"
    rm $f
    flink=${f:0:-4}1
    ln -s "../../archive/$dir/$flink.pem" $f
  done
  cd ..
  cd ..
done
