#!/bin/sh

BACKUP_DIR="/tmp"
BACKUP_NAME=nginx.tar
REMOTE_DIR=/volume1/veeam/raspi

echo "Creating ZIP"
cd /root
tar -cf "$BACKUP_DIR/$BACKUP_NAME" nginx

echo "Copy to remote location"
scp -P 222 "$BACKUP_DIR/$BACKUP_NAME" "root@192.168.1.220:$REMOTE_DIR"

# Remove created zip file
rm "$BACKUP_DIR/$BACKUP_NAME"
