#!/bin/bash

if [[ -f "$1" ]]; then
  echo "Selected file $1"
else
  echo "Usage: $0 <path>"
  exit 1
fi

FILE=$1
TEMPFILE=$1.tmp

function replace {
  # replace newline
  cat $FILE | tr '\n' ' ' > $TEMPFILE
  # replace accentate
  sed -i 's/`a/à/g' $TEMPFILE
  sed -i 's/`e/è/g' $TEMPFILE
  sed -i 's/`i/ì/g' $TEMPFILE
  sed -i 's/`o/ò/g' $TEMPFILE
  # caratteri speciali
  sed -i "s/’/'/g" $TEMPFILE
  sed -i 's/”/"/g' $TEMPFILE
  # word break
  sed -i 's/-//g' $TEMPFILE

  cp $FILE $FILE.bak
  mv $TEMPFILE $FILE
}

while inotifywait -e close_write $FILE
do
  echo "Replacing"
  replace
done