#!/bin/bash

WORDPRESS_DIR=/root/wordpress
DOCKER_PS=$( docker ps | grep wordpress | awk '{print $11}' )

if [[ $DOCKER_PS == "wordpress" ]]; then
	echo "Wordpress is already on"
else
	echo "Starting wordpress"
	cd $WORDPRESS_DIR
	docker-compose up -d &> /dev/null &
fi


